# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import movies_pb2 as movies__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in movies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMoviesTitle = channel.unary_unary(
                '/movies.MovieService/GetMoviesTitle',
                request_serializer=movies__pb2.MovieTitleRequest.SerializeToString,
                response_deserializer=movies__pb2.MovieTitleResponse.FromString,
                _registered_method=True)
        self.AddMovie = channel.unary_unary(
                '/movies.MovieService/AddMovie',
                request_serializer=movies__pb2.AddMovieRequest.SerializeToString,
                response_deserializer=movies__pb2.AddMovieResponse.FromString,
                _registered_method=True)
        self.LookupDate = channel.unary_unary(
                '/movies.MovieService/LookupDate',
                request_serializer=movies__pb2.MovieLookupRequest.SerializeToString,
                response_deserializer=movies__pb2.MovieLookupResponse.FromString,
                _registered_method=True)


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMoviesTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMoviesTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesTitle,
                    request_deserializer=movies__pb2.MovieTitleRequest.FromString,
                    response_serializer=movies__pb2.MovieTitleResponse.SerializeToString,
            ),
            'AddMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovie,
                    request_deserializer=movies__pb2.AddMovieRequest.FromString,
                    response_serializer=movies__pb2.AddMovieResponse.SerializeToString,
            ),
            'LookupDate': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupDate,
                    request_deserializer=movies__pb2.MovieLookupRequest.FromString,
                    response_serializer=movies__pb2.MovieLookupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movies.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movies.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMoviesTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/GetMoviesTitle',
            movies__pb2.MovieTitleRequest.SerializeToString,
            movies__pb2.MovieTitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/AddMovie',
            movies__pb2.AddMovieRequest.SerializeToString,
            movies__pb2.AddMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/LookupDate',
            movies__pb2.MovieLookupRequest.SerializeToString,
            movies__pb2.MovieLookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
