# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\x12\x06movies\"e\n\x05Movie\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x14\n\x0crelease_year\x18\x03 \x01(\x05\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x16\n\x0e\x61verage_rating\x18\x05 \x01(\x02\"\x13\n\x11MovieTitleRequest\"$\n\x12MovieTitleResponse\x12\x0e\n\x06titles\x18\x01 \x03(\t\"W\n\x0f\x41\x64\x64MovieRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64irector\x18\x02 \x01(\t\x12\x14\n\x0crelease_year\x18\x03 \x01(\x05\x12\r\n\x05genre\x18\x04 \x01(\t\"#\n\x10\x41\x64\x64MovieResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x12MovieLookupRequest\x12\r\n\x05title\x18\x01 \x01(\t\"+\n\x13MovieLookupResponse\x12\x14\n\x0crelease_year\x18\x01 \x01(\x05\x32\xdd\x01\n\x0cMovieService\x12G\n\x0eGetMoviesTitle\x12\x19.movies.MovieTitleRequest\x1a\x1a.movies.MovieTitleResponse\x12=\n\x08\x41\x64\x64Movie\x12\x17.movies.AddMovieRequest\x1a\x18.movies.AddMovieResponse\x12\x45\n\nLookupDate\x12\x1a.movies.MovieLookupRequest\x1a\x1b.movies.MovieLookupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIE']._serialized_start=24
  _globals['_MOVIE']._serialized_end=125
  _globals['_MOVIETITLEREQUEST']._serialized_start=127
  _globals['_MOVIETITLEREQUEST']._serialized_end=146
  _globals['_MOVIETITLERESPONSE']._serialized_start=148
  _globals['_MOVIETITLERESPONSE']._serialized_end=184
  _globals['_ADDMOVIEREQUEST']._serialized_start=186
  _globals['_ADDMOVIEREQUEST']._serialized_end=273
  _globals['_ADDMOVIERESPONSE']._serialized_start=275
  _globals['_ADDMOVIERESPONSE']._serialized_end=310
  _globals['_MOVIELOOKUPREQUEST']._serialized_start=312
  _globals['_MOVIELOOKUPREQUEST']._serialized_end=347
  _globals['_MOVIELOOKUPRESPONSE']._serialized_start=349
  _globals['_MOVIELOOKUPRESPONSE']._serialized_end=392
  _globals['_MOVIESERVICE']._serialized_start=395
  _globals['_MOVIESERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
